### ISSUE TITLE
Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by fjc0k** [innocenzi/rename#1]
node: v12.22.1

![image](https://user-images.githubusercontent.com/13151189/124704852-55bb7800-df27-11eb-9438-72f383d9e141.png)

https://github.com/nodejs/node/issues/35740#issuecomment-713778857

![image](https://user-images.githubusercontent.com/13151189/124704721-1a20ae00-df27-11eb-9e7d-aa33f35fc238.png)

**Comment by innocenzi** [comment]
Hey, I suggest you update to the [current LTS](https://nodejs.org/en/) of Node, though if you'd rather not I'd accept a PR that use the second syntax.
