### ISSUE TITLE
Support glob for rename targets

### ISSUE THREAD

**Issue by antfu** [innocenzi/rename#2]
```ts
rn **/*.ts
```

**Comment by innocenzi** [comment]
I'm conflicted about the implementation for this. Currently, the first argument is optional and defines the directory in which to perform the scan. 

I see a few options: 
- Keep that argument, so the glob can be used like this: `rn . **/*.ts` (with `.` being the current directory)
- Remove that argument altogether, only use globs: `rn src/*.ts`
- Move the argument to a named one: `rn **/*.ts --dir src`

Personally I prefer the third one, but I'd like your input before committing.

**Comment by antfu** [comment]
I personally would prefer the third one as well. Ideally, maybe you can support them both by check the the argument is not a glob and isDirectory to fallback to the dir scanning mode.
